### ISSUE TITLE
All properties with zillow_status 'RecentlySold' have a zillow_price of 0

### ISSUE THREAD

**Issue by finnoshea** [finnoshea/AffordableTravelTime#4]
@nadnerbity I'm not sure why they are all zero, is the scraping missing something?

**Comment by nadnerbity** [comment]
How many are there?

This is because there is no sale price.  I'm not sure why they are marked as "RecentlySold" they appear to be foreclosures with an estimated foreclosure price.

For example:
18541550,3109 Andrade Ave,RICHMOND,CA,94804,,0,-122.336914,37.94812,RecentlySold,SINGLE_FAMILY,2019-01-05T13:49:00.359324
18534211,118 S 37th St,RICHMOND,CA,94804,,0,-122.334442,37.930453,RecentlySold,SINGLE_FAMILY,2019-01-05T13:49:00.370107

**Comment by nadnerbity** [comment]
I just noticed that those properties have been posted for 800+ days and some have non-house pictures.  I'll See about grabbing the days posted thing so we can ignore these types of entries.

**Comment by nadnerbity** [comment]
Closed. Fix in f1d5d7050eca830b19156d2b3f309f7989afa41f.

The zero price isn't a bug, there is no price because the property is a rather old listing.
